import type { NextPage, NextComponentType } from "next";
import { useState, useRef } from "react";
import Head from "next/head";
import styles from "../../styles/test-confirmation.module.scss";
import Navigation from "../../components/nav";
import Footer from "../../components/Footer";
// import Link from "next/link";
import Image from 'next/image';
import axios from 'axios';

const MainContent: NextComponentType = () => {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(false);
    const [responseData, setResponseData] = useState(null);
    const [hideButton, setHideButton] = useState(false);
    const formElem = useRef(null);

    const clearData = () => {
        formElem.current.reset();
        setData(null);
        setLoading(false);
        setResponseData(null);
    }

    // useEffect(()=>{
    //   console.log(formElem.current);
    // }, [formElem])

    const handleChange = (e) => {
        const { name, value } = e.target;
        if (value) {
            setData(prev => prev ? ({ ...prev, [name]: value }) : { [name]: value });
        }
    }

    const handleSubmit = async e => {
        setHideButton(true);
        console.log(data);
        setLoading(true);
        e.preventDefault();
        if (data) {
            const responseData2 = await axios.post('/api/user', data)
                .then((res) => { console.log(res); return res.data })
                .catch(err => { console.log(err.response.data); return err.response.data });
            console.log(responseData2);
            setResponseData(responseData2);
            setLoading(false);
            setHideButton(false);
            // if(responseData2.success){
            //   e.reset();
            // }

        }
    }
    return (
        <div>
            <div className={styles.titleSection}>
                <h2 className="">Select an option</h2>
            </div>
            <div className={styles.contentSection}>
                <div>
                    <form action="#" onSubmit={handleSubmit} ref={formElem}>
                        <input type="text" name="fullname" placeholder="Fullname" id="" onChange={handleChange} required />
                        <input type="email" name="email" placeholder="Email" id="" onChange={handleChange} required />
                        {!hideButton && <input type="submit" value="Submit" />}
                    </form>
                </div>
            </div>
        </div>
    )
}
const SideBar: NextComponentType = () => {
    return (
        <div className={styles.sideBar}>
            <div className={styles.sideTitle}>
                <h2 className="">Confirm <br /> Your <br /> Availability</h2>
            </div>
            <div className={styles.sideFooter}>
                <Image src="/images/test-confirmation/AULogo(white).svg" width={90.46} height={84} alt="Aluvium University" />
            </div>
        </div>
    )
}

const Students: NextPage = () => {
    // const [currentView, setCurrentView] = useState('overview');

    return (
        <div className={styles.container}>
            <Head>
                <title>Students Resources | Alluvium University</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className="z-10">
                    <Navigation />
                </section>
                <section className="py-2 mb-5">
                    <div className={`${styles.main} container-fluid container-sm row p-0`}>
                        <div className="col-sm-5 p-0 pe-md-4 mb-5 mb-md-0">
                            <SideBar />
                        </div>
                        <div className="col-sm-6">
                            <MainContent />
                        </div>
                    </div>
                </section>
                <section>
                    <Footer />
                </section>
            </main>
        </div>
    );
};

export default Students;
