import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/nav";
import Footer from "../components/Footer";
import Texthero from "../components/Texthero";
import Breadcrumb from "../components/Breadcrumb";
import Form from "../components/contact/Form";
import Card from "../components/contact/Card";
import Content from "../components/contact/Content";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact | Alluvium University</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="">
          <Navigation />
        </section>
        <section>
          <Texthero />
          <Breadcrumb title="Contact" />
        </section>
        <section className="container">
          <h2>Reach Out to Alluvium University</h2>
          <div className="row my-4">
            <div className="col-md-8">
              <iframe frameBorder="0" style={{height: '100%', width: '100%%', border: 'none'}} src='https://forms.zohopublic.com/admin1711/form/ContactUs/formperma/ywG1UqqTEfcSggqvjWrl_fTDGN6tS6l8KxBzlvUhZUU'></iframe>
              {/* <Form /> */}
            </div>
            <div className="col-md-4">
              <Card content={<Content name={1} />} />
              <Card content={<Content name={2} />} />
              <Card content={<Content name={3} />} />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
