import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/events.module.scss";
import Navigation from "../components/nav";
import Footer from "../components/Footer";
import Breadcrumb from "../components/Breadcrumb";
import Banner from "../components/Banner";
import Search from "../components/Search";
import EventCard from "../components/event/EventCard";
import React from 'react';
import Calendar from 'react-calendar';
import 'react-calendar/dist/Calendar.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events | Alluvium University</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="">
          <Navigation />
        </section>
        <section>
          <Banner title="Events" backgroundImage={"images/event_banner.png"} />
          <Breadcrumb title="Event" />
        </section>
        <section className="container py-5">
          <div className="row pb-5">
            <div className="col-md-6"><h2>Upcoming Events</h2></div>
            <div className="col-md-6"><Search placeholder="Search events" /></div>
          </div>

          <div className="row">
            <div className="col-md-4 pl-3"><Calendar /></div>
            <div className="col-md-8 row p-0">
              {/* <EventCard />
              <EventCard />
              <EventCard /> */}
              <div className="col-md-3"></div>
              <div className="col-md-9 py-5 p-md-0">
                <h2 className={styles.noEvent}>*No upcoming event</h2>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
