import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/nav";
import Footer from "../components/Footer";
import Breadcrumb from "../components/Breadcrumb";
import Banner from "../components/Banner";
import Search from "../components/Search";
import EventCard from "../components/event/EventCard";
import EventInfo from "../components/event/EventInfo";
import Socialmedia from "../components/Socialmedia";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Event Details | Alluvium University</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="">
          <Navigation />
        </section>
        <section>
          <Banner title="Events" backgroundImage={"images/event_banner.png"}/>
          <Breadcrumb title="Event/ Alluvium University Students Admission Day" />
        </section>
        <section className="container">
			<div className="row pb-5">
				<div className="pt-5 text-center col-md-12"><h2>Alluvium University Students Admission Day</h2></div>
			</div>
			
			<div className="row">
      			<div className="col-md-9 pl-3"> 
              		<EventInfo />
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean </p>

            	</div>
				<div className="col-md-2 card p-4">
					<div className="">
					<h6>Add events to </h6>
                    <hr />
					<ul className="os-social" style={{display: 'flex'}}>
                        <li className=""><a href="#" rel="noreferrer" target="_blank"><img src="images/google.png" alt="twitter"/></a></li>
                        
                        <li className=""><a href="#" rel="noreferrer" target="_blank"><img src="images/apple.png" alt="facebook"/></a></li>
                        
						<li className=""><a href="#" rel="noreferrer" target="_blank"><img src="images/microsoft.png" alt="linkedin"/></a></li>
                    </ul>
					<hr />
					<Socialmedia />
					</div>
					
				</div>

				<div className="div mt-5">
					<div className="other-events">
						<h3 className="pb-4">Other Events</h3>
						<EventCard />
						<EventCard />
						<EventCard />
					</div>
				</div>
			</div>
        </section>
      </main>
      <Footer/>
    </div>
  );
};

export default Home;
