import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import ShortCut from "../components/shortcut";
import Navigation from "../components/nav";
import Event from "../components/Event";
import Testimony from "../components/Testimony";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home   |  Alluvium University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navigation />
        <Hero />
        <ShortCut />
				<Event />
				<Testimony />
      </main>
      <Footer/>
    </div>
  );
};

export default Home;
